from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.contracts.json_schemas import schema_registry


GENERATED_DIR = ROOT / "frontend" / "src" / "lib" / "generated"
RUNTIME_OUTPUT_PATH = GENERATED_DIR / "solver-contract-runtime.ts"
DTO_OUTPUT_PATH = GENERATED_DIR / "solver-contract-dto.ts"
OUTPUT_PATH = GENERATED_DIR / "solver-contract.ts"


def _property_name(value: str) -> str:
    return value if value.replace("_", "a").isalnum() and not value[0].isdigit() else json.dumps(value)


def _typescript_type(schema: Any, indent: int = 0) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "const" in schema:
        return json.dumps(schema["const"])
    if schema.get("enum"):
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for union_key in ("oneOf", "anyOf"):
        if schema.get(union_key):
            return " | ".join(_typescript_type(item, indent) for item in schema[union_key])
    if schema.get("allOf") and "properties" not in schema and "type" not in schema:
        return " & ".join(_typescript_type(item, indent) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "null" if item == "null" else _typescript_type({**schema, "type": item}, indent)
            for item in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _typescript_type(schema.get("items", {}), indent)
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if not properties:
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"Record<string, {_typescript_type(additional, indent)}>"
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        pad = " " * indent
        child_pad = " " * (indent + 2)
        rows = [
            f"{child_pad}{_property_name(name)}{' ' if name in required else '?'}: {_typescript_type(value, indent + 2)};"
            for name, value in properties.items()
        ]
        return "{\n" + "\n".join(rows) + f"\n{pad}}}"
    return "unknown"


def _dto_declarations(registry: dict[str, dict[str, Any]]) -> str:
    dto_schemas = {
        "SolverJobRequestDto": registry["job-request"],
        "SolverCapabilityResultDto": registry["capability-result"],
        "SolverHostMessageDto": registry["solver-host-message"],
        "SolverArtifactManifestDto": registry["solver-artifact-manifest"],
    }
    rows = [
        f"export type {name} = {_typescript_type(schema)};"
        for name, schema in dto_schemas.items()
    ]
    diagnostic_schema = (
        registry["capability-result"]["properties"]["diagnostics"]["properties"]["issues"]["items"]
    )
    rows.insert(1, f"export type SolverDiagnosticIssueDto = {_typescript_type(diagnostic_schema)};")
    rows.append(
        "export interface SolverContractDtoMap {\n"
        "  \"job-request\": SolverJobRequestDto;\n"
        "  \"capability-result\": SolverCapabilityResultDto;\n"
        "  \"solver-host-message\": SolverHostMessageDto;\n"
        "  \"solver-artifact-manifest\": SolverArtifactManifestDto;\n"
        "}"
    )
    return "\n\n".join(rows)


def _runtime_declarations(registry: dict[str, dict[str, Any]]) -> str:
    host_schema = registry["solver-host-message"]
    host_protocol_version = host_schema["properties"]["protocolVersion"]["const"]
    host_message_types = host_schema["properties"]["type"]["enum"]
    capability_names = _ready_capability_names(host_schema)
    schema_ids = list(registry.keys())
    job_operations = registry["job-request"]["properties"]["operation"]["enum"]
    diagnostic_severities = (
        registry["capability-result"]["properties"]["diagnostics"]["properties"]["issues"]["items"]["properties"]["severity"]["enum"]
    )
    capability_rows = "\n".join(f"  {name}: true," for name in capability_names)
    return (
        "// Generated by scripts/generate_contract_types.py from backend JSON Schemas.\n"
        "// Do not edit by hand; update the schema and regenerate this file.\n\n"
        f"export const SOLVER_HOST_PROTOCOL_VERSION = {json.dumps(host_protocol_version)} as const;\n"
        f"export const SOLVER_HOST_MESSAGE_TYPES = {json.dumps(host_message_types)} as const;\n"
        "export type SolverHostMessageType = (typeof SOLVER_HOST_MESSAGE_TYPES)[number];\n\n"
        f"export const SOLVER_SCHEMA_IDS = {json.dumps(schema_ids)} as const;\n"
        "export type SolverSchemaId = (typeof SOLVER_SCHEMA_IDS)[number];\n\n"
        "export const SOLVER_HOST_CAPABILITIES = Object.freeze({\n"
        f"{capability_rows}\n"
        "} as const);\n"
        "export type SolverHostCapability = keyof typeof SOLVER_HOST_CAPABILITIES;\n\n"
        f"export const SOLVER_JOB_OPERATION_VALUES = {json.dumps(job_operations)} as const;\n"
        "export type SolverJobOperation = (typeof SOLVER_JOB_OPERATION_VALUES)[number];\n\n"
        f"export const SOLVER_DIAGNOSTIC_SEVERITY_VALUES = {json.dumps(diagnostic_severities)} as const;\n"
        "export type SolverDiagnosticSeverity = (typeof SOLVER_DIAGNOSTIC_SEVERITY_VALUES)[number];\n"
    )


def _barrel_declarations() -> str:
    return (
        "// Generated by scripts/generate_contract_types.py from backend JSON Schemas.\n"
        "// Do not edit by hand; update the schema and regenerate this file.\n\n"
        'export * from "./solver-contract-runtime.ts";\n'
        'export * from "./solver-contract-dto.ts";\n'
    )


def _ready_capability_names(host_schema: dict[str, Any]) -> list[str]:
    for condition in host_schema["allOf"]:
        condition_type = condition.get("if", {}).get("properties", {}).get("type", {}).get("const")
        capability_schema = (
            condition.get("then", {})
            .get("properties", {})
            .get("payload", {})
            .get("properties", {})
            .get("capabilities")
        )
        if condition_type == "archsight.solver.ready" and capability_schema:
            return list(capability_schema["required"])
    raise ValueError("solver-host-message schema 缺少 ready capabilities 契约")


def render_typescript() -> dict[str, str]:
    registry = schema_registry()
    return {
        "runtime": _runtime_declarations(registry),
        "dto": (
            "// Generated by scripts/generate_contract_types.py from backend JSON Schemas.\n"
            "// Do not edit by hand; update the schema and regenerate this file.\n\n"
            f"{_dto_declarations(registry)}\n"
        ),
        "barrel": _barrel_declarations(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="从后端 JSON Schema 生成前端稳定契约类型。")
    parser.add_argument("--check", action="store_true", help="只检查已提交产物是否最新。")
    args = parser.parse_args()
    expected = render_typescript()

    if args.check:
        checks = {
            RUNTIME_OUTPUT_PATH: expected["runtime"],
            DTO_OUTPUT_PATH: expected["dto"],
            OUTPUT_PATH: expected["barrel"],
        }
        for path, content in checks.items():
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if actual != content:
                print(f"跨栈契约类型已漂移，请运行: python {Path(__file__).name}")
                return 1
        print("跨栈契约类型与后端 JSON Schema 一致")
        return 0

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in (
        (RUNTIME_OUTPUT_PATH, expected["runtime"]),
        (DTO_OUTPUT_PATH, expected["dto"]),
        (OUTPUT_PATH, expected["barrel"]),
    ):
        path.write_text(content, encoding="utf-8")
    print(
        "已生成 "
        f"{RUNTIME_OUTPUT_PATH.relative_to(ROOT)}, "
        f"{DTO_OUTPUT_PATH.relative_to(ROOT)}, "
        f"{OUTPUT_PATH.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
