from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.contracts.json_schemas import schema_registry


OUTPUT_PATH = ROOT / "frontend" / "src" / "lib" / "generated" / "solver-contract.ts"


def _ready_capability_names(host_schema: dict[str, Any]) -> list[str]:
    for condition in host_schema["allOf"]:
        condition_type = condition.get("if", {}).get("properties", {}).get("type", {}).get("const")
        capability_schema = (
            condition.get("then", {})
            .get("properties", {})
            .get("payload", {})
            .get("properties", {})
            .get("capabilities")
        )
        if condition_type == "archsight.solver.ready" and capability_schema:
            return list(capability_schema["required"])
    raise ValueError("solver-host-message schema 缺少 ready capabilities 契约")


def render_typescript() -> str:
    registry = schema_registry()
    host_schema = registry["solver-host-message"]
    host_protocol_version = host_schema["properties"]["protocolVersion"]["const"]
    host_message_types = host_schema["properties"]["type"]["enum"]
    capability_names = _ready_capability_names(host_schema)
    job_operations = registry["job-request"]["properties"]["operation"]["enum"]
    diagnostic_severities = (
        registry["capability-result"]["properties"]["diagnostics"]["properties"]["issues"]["items"]["properties"]["severity"]["enum"]
    )

    capability_rows = "\n".join(f"  {name}: true," for name in capability_names)
    return (
        "// Generated by scripts/generate_contract_types.py from backend JSON Schemas.\n"
        "// Do not edit by hand; update the schema and regenerate this file.\n\n"
        f"export const SOLVER_HOST_PROTOCOL_VERSION = {json.dumps(host_protocol_version)} as const;\n"
        f"export const SOLVER_HOST_MESSAGE_TYPES = {json.dumps(host_message_types)} as const;\n"
        "export type SolverHostMessageType = (typeof SOLVER_HOST_MESSAGE_TYPES)[number];\n\n"
        "export const SOLVER_HOST_CAPABILITIES = Object.freeze({\n"
        f"{capability_rows}\n"
        "} as const);\n"
        "export type SolverHostCapability = keyof typeof SOLVER_HOST_CAPABILITIES;\n\n"
        f"export const SOLVER_JOB_OPERATION_VALUES = {json.dumps(job_operations)} as const;\n"
        "export type SolverJobOperation = (typeof SOLVER_JOB_OPERATION_VALUES)[number];\n\n"
        f"export const SOLVER_DIAGNOSTIC_SEVERITY_VALUES = {json.dumps(diagnostic_severities)} as const;\n"
        "export type SolverDiagnosticSeverity = (typeof SOLVER_DIAGNOSTIC_SEVERITY_VALUES)[number];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="从后端 JSON Schema 生成前端稳定契约类型。")
    parser.add_argument("--check", action="store_true", help="只检查已提交产物是否最新。")
    args = parser.parse_args()
    expected = render_typescript()

    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if actual != expected:
            print(f"跨栈契约类型已漂移，请运行: python {Path(__file__).name}")
            return 1
        print("跨栈契约类型与后端 JSON Schema 一致")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"已生成 {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
